# Generated by Django 5.0.9 on 2025-02-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0061_garnishment_fees_rules_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='garnishment_fees_rules',
        ),
    ]
