# Generated by Django 5.0.9 on 2025-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0062_delete_garnishment_fees_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='garnishment_fees_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('maximum_fee_deduction', models.CharField(max_length=255)),
                ('per_pay_period', models.DecimalField(decimal_places=2, max_digits=250)),
                ('per_month', models.DecimalField(decimal_places=2, max_digits=250)),
                ('per_remittance', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
        ),
    ]
