# Generated by Django 5.0.9 on 2025-02-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0063_garnishment_fees_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garnishment_fees_rules',
            name='state',
        ),
    ]
