# Generated by Django 5.0.9 on 2025-02-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0064_remove_garnishment_fees_rules_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garnishment_fees_rules',
            old_name='rule',
            new_name='state',
        ),
    ]
