# Generated by Django 5.0.9 on 2025-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0066_rename_state_garnishment_fees_rules_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='disposable_earning_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('disposable_earnings', models.CharField(max_length=255)),
            ],
        ),
    ]
