# Generated by Django 5.0.9 on 2025-02-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0067_disposable_earning_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Tax_details',
        ),
    ]
