# Generated by Django 5.0.9 on 2025-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0068_delete_department_delete_location_delete_tax_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='withholding_limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255)),
                ('withholding_limit', models.CharField(max_length=255)),
                ('supports_2nd_family', models.CharField(max_length=255)),
                ('arrears_of_more_than_12_weeks', models.CharField(max_length=255)),
                ('JSON_Key', models.CharField(max_length=255)),
                ('no_of_orders', models.CharField(max_length=255)),
                ('weekly_de', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='withholding_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=255)),
                ('abv', models.CharField(max_length=255)),
                ('allocation_method', models.CharField(max_length=255)),
                ('withholding_limit', models.CharField(max_length=255)),
            ],
        ),
    ]
