# Generated by Django 5.0.9 on 2025-02-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0069_withholding_limit_withholding_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='withholding_limit',
        ),
    ]
