# Generated by Django 5.0.9 on 2025-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0070_delete_withholding_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='withholding_limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255)),
                ('withholding_limit', models.CharField(max_length=255)),
                ('supports_2nd_family', models.CharField(max_length=255)),
                ('arrears_of_more_than_12_weeks', models.CharField(max_length=255)),
                ('json_Key', models.CharField(max_length=255)),
                ('no_of_orders', models.CharField(max_length=255)),
                ('weekly_de', models.CharField(max_length=255)),
            ],
        ),
    ]
