# Generated by Django 5.0.9 on 2025-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0071_withholding_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_detail',
            name='garnishment_fees_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
