# Generated by Django 5.0.9 on 2025-02-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0072_employee_detail_garnishment_fees_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_detail',
            name='garnishment_fees_suspended_till',
            field=models.DateField(default='2025-02-28'),
            preserve_default=False,
        ),
    ]
