# Generated by Django 5.0.9 on 2025-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0073_employee_detail_garnishment_fees_suspended_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='garnishment_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('pay_period', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
