# Generated by Django 5.0.9 on 2025-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0074_garnishment_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnishment_fees',
            name='rules',
            field=models.CharField(default='Rule_1', max_length=255),
            preserve_default=False,
        ),
    ]
