# Generated by Django 5.0.9 on 2025-02-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0075_garnishment_fees_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garnishment_fees',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
