# Generated by Django 5.0.9 on 2025-02-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0076_alter_garnishment_fees_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnishment_fees',
            name='payable_by',
            field=models.CharField(default='employee', max_length=255),
            preserve_default=False,
        ),
    ]
