# Generated by Django 5.0.9 on 2025-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0077_garnishment_fees_payable_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garnishment_fees',
            name='payable_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
