# Generated by Django 5.0.9 on 2025-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0079_employee_detail_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
