# Generated by Django 5.0.9 on 2025-02-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0080_alter_employee_detail_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnishment_order',
            name='fein',
            field=models.CharField(default='12-3456789', max_length=254),
            preserve_default=False,
        ),
    ]
