# Generated by Django 5.0.9 on 2025-02-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0081_garnishment_order_fein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garnishment_order',
            name='cid',
        ),
    ]
