# Generated by Django 5.0.9 on 2025-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0082_remove_garnishment_order_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_income_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('social_security_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicare_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('union_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wilmington_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_insurance_pretax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('industrial_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('life_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CaliforniaSDI', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_detail',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='employee_detail',
            name='pay_period',
        ),
    ]
