# Generated by Django 5.0.9 on 2025-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0083_payrolltaxes_remove_employee_detail_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ee_id', models.CharField(max_length=20, unique=True)),
                ('case_id', models.CharField(max_length=20)),
                ('work_state', models.CharField(max_length=50)),
                ('no_of_exemption_including_self', models.FloatField()),
                ('pay_period', models.CharField(max_length=20)),
                ('filing_status', models.CharField(max_length=20)),
                ('age', models.FloatField()),
                ('is_blind', models.BooleanField()),
                ('is_spouse_blind', models.BooleanField()),
                ('spouse_age', models.FloatField()),
                ('support_second_family', models.CharField(max_length=10)),
                ('no_of_student_default_loan', models.FloatField()),
                ('arrears_greater_than_12_weeks', models.CharField(max_length=10)),
                ('no_of_dependent_exemption', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GarnishmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('ordered_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrear_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_medical_support', models.DecimalField(decimal_places=2, max_digits=10)),
                ('past_due_medical_support', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_spousal_support', models.DecimalField(decimal_places=2, max_digits=10)),
                ('past_due_spousal_support', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='payrolltaxes',
            old_name='CaliforniaSDI',
            new_name='california_sdi',
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='commission_and_bonus',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='ee_id',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='exemption_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='non_accountable_allowances',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolltaxes',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
