# Generated by Django 5.0.9 on 2025-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0084_employeefinancialdata_garnishmentdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefinancialdata',
            name='type',
        ),
        migrations.AddField(
            model_name='garnishmentdata',
            name='garnishment_type',
            field=models.CharField(default='Child Support', max_length=50),
            preserve_default=False,
        ),
    ]
