# Generated by Django 5.0.9 on 2025-03-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0085_remove_employeefinancialdata_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeFinancialData',
            new_name='EmployeeData',
        ),
    ]
