# Generated by Django 5.0.9 on 2025-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0086_rename_employeefinancialdata_employeedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolltaxes',
            name='ee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
