# Generated by Django 5.0.9 on 2025-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0087_alter_payrolltaxes_ee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='ee_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='garnishmentdata',
            name='case_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payrolltaxes',
            name='ee_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
