# Generated by Django 5.0.9 on 2025-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0088_alter_employeedata_ee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='arrears_greater_than_12_weeks',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='case_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='filing_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='pay_period',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='support_second_family',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='garnishmentdata',
            name='case_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='garnishmentdata',
            name='garnishment_type',
            field=models.CharField(max_length=255),
        ),
    ]
