# Generated by Django 5.0.9 on 2025-03-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0091_delete_calculation_data_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garnishment_order',
            name='record_import',
        ),
    ]
