# Generated by Django 5.0.9 on 2025-03-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0093_rename_state_garnishment_order_work_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='work_state',
            new_name='state',
        ),
    ]
