# Generated by Django 5.0.9 on 2025-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0094_rename_work_state_employee_detail_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
