# Generated by Django 5.0.9 on 2025-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0095_apilog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='state',
            new_name='pay_period',
        ),
        migrations.AddField(
            model_name='employee_detail',
            name='work_state',
            field=models.CharField(default='florida', max_length=255),
            preserve_default=False,
        ),
    ]
