# Generated by Django 5.0.9 on 2025-03-27 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0096_rename_state_employee_detail_pay_period_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APILog',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='additional_info',
            new_name='traceback',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='action',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='details',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='logentry',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='function_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='level',
            field=models.CharField(default='error', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='logger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='message',
            field=models.TextField(default='error'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
