# Generated by Django 5.0.9 on 2025-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0098_logdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdata',
            old_name='level',
            new_name='status',
        ),
        migrations.AddField(
            model_name='logdata',
            name='api_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdata',
            name='endpoint',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdata',
            name='status_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
