# Generated by Django 5.0.9 on 2025-03-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0100_rename_employer_id_employer_profile_employers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_profile',
            old_name='employers_id',
            new_name='employer_id',
        ),
    ]
