# Generated by Django 5.0.9 on 2025-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0101_rename_employers_id_employer_profile_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='is_blind',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='no_of_exemption_including_self',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
