# Generated by Django 5.0.9 on 2025-04-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0102_alter_employeedata_age_alter_employeedata_is_blind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='filing_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='pay_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
