# Generated by Django 5.0.9 on 2025-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0103_alter_employeedata_filing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
