# Generated by Django 5.0.9 on 2025-04-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0104_alter_employer_profile_employer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_profile',
            old_name='employer_id',
            new_name='id',
        ),
    ]
