# Generated by Django 5.0.9 on 2025-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0105_rename_employer_id_employer_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_profile',
            old_name='id',
            new_name='employer_id',
        ),
    ]
