# Generated by Django 5.0.9 on 2025-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0106_rename_id_employer_profile_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
