# Generated by Django 5.0.9 on 2025-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0107_alter_employer_profile_employer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_profile',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='federal_employer_identification_number',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='employer_profile',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='employer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
