# Generated by Django 5.0.9 on 2025-04-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0109_employer_profile_city_employer_profile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_profile',
            old_name='employer_id',
            new_name='id',
        ),
    ]
