export const StateList = [
  { id: 46, label: 'Alaska' },
    { id: 1, label: 'Alabama' },
    { id: 2, label: 'Arizona' },
    { id: 47, label: 'Arkansas' },
    { id: 3, label: 'California' },
    { id: 4, label: 'Colorado' },
    { id: 5, label: 'Connecticut' },
    { id: 6, label: 'Florida' },
    { id: 7, label: 'Georgia' },
    { id: 8, label: 'Idaho' },
    { id: 9, label: 'Illinois' },
    { id: 10, label: 'Indiana' },
    { id: 11, label: 'Iowa' },
    { id: 12, label: 'Kansas' },
    { id: 13, label: 'Kentucky' },
    { id: 14, label: 'Louisiana' },
    { id: 15, label: 'Maine' },
    { id: 16, label: 'Maryland' },
    { id: 17, label: 'Massachusetts' },
    { id: 18, label: 'Michigan' },
    { id: 19, label: 'Minnesota' },
    { id: 20, label: 'Mississippi' },
    { id: 21, label: 'Missouri' },
    { id: 22, label: 'Montana' },
    { id: 23, label: 'Nebraska' },
    { id: 24, label: 'Nevada' },
    { id: 25, label: 'New Hampshire' },
    { id: 26, label: 'New Jersey' },
    { id: 27, label: 'New Mexico' },
    { id: 28, label: 'North Carolina' },
    { id: 29, label: 'North Dakota' },
    { id: 30, label: 'Ohio' },
    { id: 31, label: 'Oklahoma' },
    { id: 32, label: 'Oregon' },
    { id: 33, label: 'Pennsylvania' },
    { id: 34, label: 'Rhode Island' },
    { id: 35, label: 'South Carolina' },
    { id: 36, label: 'South Dakota' },
    { id: 37, label: 'Tennessee' },
    { id: 38, label: 'Texas' },
    { id: 39, label: 'Utah' },
    { id: 40, label: 'Vermont' },
    { id: 41, label: 'Virginia' },
    { id: 42, label: 'Washington' },
    { id: 43, label: 'West Virginia' },
    { id: 44, label: 'Wisconsin' },
    { id: 45, label: 'Wyoming' },
    { id: 48, label: 'Delaware' },
    { id: 49, label: 'Hawaii' },
    { id: 50, label: 'New York' },
  ];
  
  export const GenderList = [
    { id: 1, label: 'Male' },
    { id: 2, label: 'Female' },
    { id: 3, label: 'Other' }
  ];

  export const PeriodList = [
    { id: 1, label: 'Weekly' },
    { id: 2, label: 'Biweekly' },
    { id: 3, label: 'SemiMonthly' },
    { id: 4, label: 'Monthly' }
  ];

  export const FillingStatusList = [
    { id: 1, label: 'Married filing separate' },
    { id: 2, label: 'Married Filing Joint Return' },
    { id: 3, label: 'Single' },
    { id: 4, label: 'Head of Household' }
  ];

  export const StateCreditorList = [
    { id: 1, label: "Alabama" },
    { id: 2, label: "Arkansas" },
    { id: 3, label: "Delaware" },
    { id: 4, label: "Florida" },
    { id: 5, label: "Idaho" },
    { id: 6, label: "Indiana" },
    { id: 7, label: "Kansas" },
    { id: 8, label: "Kentucky" },
    { id: 9, label: "Louisiana" },
    { id: 10, label: "Michigan" },
    { id: 11, label: "Mississippi" },
    { id: 12, label: "Montana" },
    { id: 13, label: "New Hampshire" },
    { id: 14, label: "New Jersey" },
    { id: 15, label: "Ohio" },
    { id: 16, label: "Oklahoma" },
    { id: 17, label: "Rhode Island" },
    { id: 18, label: "Texas" },
    { id: 19, label: "Utah" },
    { id: 20, label: "Vermont" },
    { id: 21, label: "Wyoming" },
    { id: 22, label: "West Virginia" },
    { id: 23, label: "Virginia" },
    { id: 24, label: "Wisconsin" },
    { id: 25, label: "Washington" },
    { id: 26, label: "New York" },
    { id: 27, label: "Nebraska" },
    { id: 28, label: "Missouri" },
    { id: 29, label: "Massachusetts" },
    { id: 30, label: "Maryland" },
    { id: 31, label: "South Dakota" },
    { id: 32, label: "Maine" },
    { id: 33, label: "Illinois" },
    { id: 34, label: "Hawaii" },
    { id: 35, label: "Georgia" },
    { id: 36, label: "Connecticut" },
    { id: 37, label: "California" },
    { id: 38, label: "Arizona" },
    { id: 39, label: "Tennessee" },
    { id: 40, label: "Colorado" },
  ];

  export const StateLevyContactList = [
    { id: 1, label: "Alabama" },
    { id: 2, label: "Arkansas" },
    { id: 3, label: "Delaware" },
    { id: 4, label: "California" },
    { id: 5, label: "Georgia" },
    { id: 6, label: "Hawaii" },
    { id: 7, label: "Idaho" },
    { id: 8, label: "Illinois" },
    { id: 9, label: "Indiana" },
    { id: 10, label: "Iowa" },
    { id: 11, label: "Louisiana" },
    { id: 12, label: "Massachusetts" },
    { id: 13, label: "Minnesota" },
    { id: 14, label: "Mississippi" },
    { id: 15, label: "Missouri" },
    { id: 16, label: "Montana" },
    { id: 17, label: "New Mexico" },
    { id: 18, label: "New Jersey" },
    { id: 19, label: "New York" },
    { id: 20, label: "North Carolina" },
    { id: 21, label: "Oregon" },
    { id: 22, label: "Pennsylvania" },
    { id: 23, label: "Utah" },
    { id: 24, label: "Vermont" },
    { id: 25, label: "Virginia" },
    { id: 26, label: "Wisconsin" },
  ];
